<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>dvcli</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DepotVault.Core\DepotVault.Core.csproj" />
  </ItemGroup>

</Project>
